### ISSUE TITLE
Choose Database -> Connect to Spring

### ISSUE THREAD

**Issue by Grimaldus12** [hhu-propra2/abschlussprojekt-bugrog-morgoth-ush-parse#27]
Choose a specific database and add the connection info to application.properties

**Comment by brokelyn** [comment]
We should use H2 for dev properties. In production properties we can use prostgres or mysql because that were the databases from last project

**Comment by claussmann** [comment]
At initialization i already included the mysql-driver. I think we should write a dockerfile for setting up both, the project and the mysql server (maybe also the Pro-Pay?). Regardless of what you use for develop on your machine, the CI should always use the dockerfile.
