### ISSUE TITLE
Max values for database

### ISSUE THREAD

**Issue by brokelyn** [hhu-propra2/abschlussprojekt-bugrog-morgoth-ush-parse#64]
we have issues when saving large descriptions to the database. we need to overthink some field and their max charsize.

**Comment by tnfru** [comment]
Can you specify which description you mean?

**Comment by claussmann** [comment]
We mean the description of items. We would like to save (e.g.) 512 chars for the full description. In the item-card overview we will only show like the first 100 chars?

**Comment by Grimaldus12** [comment]
Why are we showing the description in the item-card view though?
It's ment to specify all important information around the item, the title should be enough for the overview.

**Comment by Grimaldus12** [comment]
Its now limited to 2000 characters.
